name: action-notify-on-change
description: 'Post useful slack messages when PRs are created'
inputs:
  slack-token:
    description: Token for slack messages
    required: true
  github-token:
    description: Token for github messages
    required: true

runs:
  using: "composite"
  steps:
    - uses: cresta/action-notify-on-change/action-notify-on-change@v1
      id: action-notify-on-change
      with:
        slack-token: ${{ inputs.slack-token }}
        github-token: ${{ inputs.github-token }}