name: action-notify-on-change
description: Runs the main logic
inputs:
  slack-token:
    description: Token for slack messages
    required: true
  github-token:
    description: Token for github messages
    required: true
runs:
  using: docker
  image: 'Dockerfile'